language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t sandeepb3245/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sandeepb3245/react-test npm run test

after_success:
  - docker build -t sandeepb3245/multi-client ./client
  - docker build -t sandeepb3245/multi-nginx ./nginx
  - docker build -t sandeepb3245/multi-server ./server
  - docker build -t sandeepb3245/multi-worker ./worker
  #log in to docker hub account to push the above prod build docker images
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_ID --password-stdin
  #now take the above images and push to dokcer hub repo
  - docker push sandeepb3245/multi-client
  - docker push sandeepb3245/multi-nginx
  - docker push sandeepb3245/multi-server
  - docker push sandeepb3245/multi-worker